version: "3"
services:
  mysql:
    container_name: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - ./.env
    restart: always
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 8003:3306
    networks:
      - spoiler_labeling
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8004:80
    env_file:
      - ./.env
    restart: always
    tty: true
    depends_on:
      - mysql
    networks:
      - spoiler_labeling
  
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 8005:8000
    env_file:
      - ./.env
    restart: always
    tty: true
    depends_on:
      - mysql
    networks:
      - spoiler_labeling

volumes:
  mysql:

networks:
  spoiler_labeling:
    driver: bridge
